### ISSUE TITLE
How to Compile

### ISSUE THREAD

**Issue by mdrain18** [Epicguru/Rimworld-Auto-Documentation#2]
Is there anyway you can add notes on how to compile? 
Or can I send you notes on how to compile and you post them :)

**Comment by Epicguru** [comment]
Like it says [in the readme](https://github.com/Epicguru/Rimworld-Auto-Documentation#using-the-generator), you can just download the compiled generator from [the release section here](https://github.com/Epicguru/Rimworld-Auto-Documentation/releases/latest).

You then run the generator following the instructions in the readme.

I can update this to Rimworld 1.5 but I don't own the DLC so if you want that, you'll have to generate it yourself.

**Comment by mdrain18** [comment]
Oh, I wasn't looking for a how to. Others were asking for it so I posted here. I have it compiled for 1.5 already and am more than happy to send some screenshots to you to post to help others build it and run it.

**Comment by Epicguru** [comment]
I have slightly adjusted the readme to be more clear about how to pass arguments (folders) into the tool, but in my opinion the instructions are already quite clear. Compiling is as simple as opening in Visual Studio and hitting Build, and the actual use of the tool is described in the readme. If you want to include image to guide other users, I welcome a PR to add them, but the way I see it this is a tool for mod developers so I expect a reasonable understanding of stuff like compiling C# and passing in command line arguments.
